// <auto-generated />
using System;
using CulinarioAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CulinarioAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240615165206_GoodDB")]
    partial class GoodDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CommentId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("Username");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Country", b =>
                {
                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryName");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Instruction", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("InstructionId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.NutritionInfo", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Fats")
                        .HasColumnType("int");

                    b.Property<int>("Fiber")
                        .HasColumnType("int");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.Property<int>("Sugar")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.ToTable("NutritionInfos");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RatingId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("Username");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<int>("RecipeType")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<int>("TotalTime")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.HasIndex("AdminUsername");

                    b.HasIndex("CountryName");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.Friendship", b =>
                {
                    b.Property<int>("FriendshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FriendshipId"));

                    b.Property<string>("FriendUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FriendshipId");

                    b.HasIndex("FriendUsername");

                    b.HasIndex("Username");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.LikedRecipe", b =>
                {
                    b.Property<int>("LikedRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikedRecipeId"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LikedRecipeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("Username", "RecipeId")
                        .IsUnique();

                    b.ToTable("LikedRecipes");
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.UserCredentials", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.UserProfile", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Comment", b =>
                {
                    b.HasOne("CulinarioAPI.Models.RecipeModels.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinarioAPI.Models.UserModels.UserProfile", "UserProfile")
                        .WithMany("Comments")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Ingredient", b =>
                {
                    b.HasOne("CulinarioAPI.Models.RecipeModels.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Instruction", b =>
                {
                    b.HasOne("CulinarioAPI.Models.RecipeModels.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.NutritionInfo", b =>
                {
                    b.HasOne("CulinarioAPI.Models.RecipeModels.Recipe", "Recipe")
                        .WithOne("NutritionInfo")
                        .HasForeignKey("CulinarioAPI.Models.RecipeModels.NutritionInfo", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Rating", b =>
                {
                    b.HasOne("CulinarioAPI.Models.RecipeModels.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinarioAPI.Models.UserModels.UserProfile", "UserProfile")
                        .WithMany("Ratings")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Recipe", b =>
                {
                    b.HasOne("CulinarioAPI.Models.UserModels.UserCredentials", "Admin")
                        .WithMany("Recipes")
                        .HasForeignKey("AdminUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinarioAPI.Models.RecipeModels.Country", "Country")
                        .WithMany("Recipes")
                        .HasForeignKey("CountryName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.Friendship", b =>
                {
                    b.HasOne("CulinarioAPI.Models.UserModels.UserProfile", "FriendUserProfile")
                        .WithMany()
                        .HasForeignKey("FriendUsername")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CulinarioAPI.Models.UserModels.UserProfile", "UserProfile")
                        .WithMany("Friendships")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FriendUserProfile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.LikedRecipe", b =>
                {
                    b.HasOne("CulinarioAPI.Models.RecipeModels.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CulinarioAPI.Models.UserModels.UserProfile", "UserProfile")
                        .WithMany("LikedRecipes")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.UserProfile", b =>
                {
                    b.HasOne("CulinarioAPI.Models.UserModels.UserCredentials", "UserCredentials")
                        .WithOne("UserProfile")
                        .HasForeignKey("CulinarioAPI.Models.UserModels.UserProfile", "Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCredentials");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Country", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("CulinarioAPI.Models.RecipeModels.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("NutritionInfo")
                        .IsRequired();

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.UserCredentials", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("UserProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("CulinarioAPI.Models.UserModels.UserProfile", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Friendships");

                    b.Navigation("LikedRecipes");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
